---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: kube-system
spec:
  secretName: webhook-certs
  issuerRef:
    name: selfsigned-issuer
  commonName: add-toleration-webhook.kube-system.svc
  dnsNames:
    - add-toleration-webhook.kube-system.svc
